function arr(v){return v==null?[]:(Array.isArray(v)?v:[v])}
function text(v){if(v==null)return '';if(typeof v==='string'||typeof v==='number')return String(v);if(typeof v==='object'&&v['#text']!=null)return String(v['#text']);return ''}
function at(v,n){return v&&typeof v==='object'?String(v['@_'+n]||v['@'+n]||''):''}
function path(o,...ks){let v=o;for(const k of ks){if(v==null)return null;v=v[k];if(Array.isArray(v))v=v[0]}return v}
function clean(v,n=2000){return String(v||'').replace(/\s+/g,' ').trim().slice(0,n)}
function iban(v){return String(v||'').replace(/[\s-]+/g,'').toUpperCase()}
function iso(v){const s=String(v||'').slice(0,10);return /^\d{4}-\d{2}-\d{2}$/.test(s)?s:null}
export function parseBankAmountToCents(raw){let s=String(raw||'').trim().replace(/\s/g,'');if(!s)return null;let sign=1;if(s[0]==='-'){sign=-1;s=s.slice(1)}else if(s[0]==='+')s=s.slice(1);if(!/^\d+(?:[.,]\d+)?$/.test(s))return null;const p=s.replace(',','.').split('.'),whole=p[0],frac=p[1]||'';if(whole.length>13)return null;let c=Number(whole)*100+Number((frac+'00').slice(0,2));if(frac.length>2&&Number(frac[2])>=5)c++;return Number.isSafeInteger(c*sign)?c*sign:null}
function first(...xs){for(const x of xs){const s=clean(text(x),500);if(s)return s}return ''}
function party(tx,dir){const p=tx&&tx.RltdPties||{};if(dir==='credit')return {name:first(path(p,'Dbtr','Nm'),path(p,'UltmtDbtr','Nm')),iban:iban(first(path(p,'DbtrAcct','Id','IBAN')))};return {name:first(path(p,'Cdtr','Nm'),path(p,'UltmtCdtr','Nm')),iban:iban(first(path(p,'CdtrAcct','Id','IBAN')))}}
function txAmt(tx){return path(tx,'AmtDtls','TxAmt','Amt')||path(tx,'AmtDtls','InstdAmt','Amt')||tx&&tx.Amt||null}
function mapCamt(stmt,ntry,tx,ei,ti,hash){
 const dir=String(text(ntry&&ntry.CdtDbtInd)).toUpperCase()==='DBIT'?'debit':'credit',node=txAmt(tx)||ntry.Amt;
 let cents=parseBankAmountToCents(text(node));if(cents==null)throw new Error('CAMT_INVALID_AMOUNT');cents=Math.abs(cents)*(dir==='debit'?-1:1);
 const refs=tx&&tx.Refs||{},p=party(tx,dir),ustrd=arr(path(tx,'RmtInf','Ustrd')).map(text).filter(Boolean);
 const e2e=first(refs.EndToEndId),bank=first(refs.AcctSvcrRef,ntry.AcctSvcrRef,ntry.NtryRef),id=first(refs.TxId,refs.InstrId,bank,e2e,String(ei+1)+'-'+String(ti+1));
 return {transaction_id:id,account_iban:iban(first(path(stmt,'Acct','Id','IBAN'),path(stmt,'Acct','Id','Othr','Id'))),counterparty_name:p.name,counterparty_iban:p.iban,booking_date:iso(first(path(ntry,'BookgDt','Dt'),path(ntry,'BookgDt','DtTm'))),value_date:iso(first(path(ntry,'ValDt','Dt'),path(ntry,'ValDt','DtTm'))),amount_cents:cents,currency:(at(node,'Ccy')||at(ntry.Amt,'Ccy')||'EUR').toUpperCase(),description:clean(ustrd.concat([text(tx&&tx.AddtlTxInf),text(ntry&&ntry.AddtlNtryInf)]).filter(Boolean).join(' ')),end_to_end_id:e2e,bank_reference:bank,credit_debit:dir,source_format:'camt053',source_file_hash:hash};
}
export function parseCamt053(parsed,hash=''){
 const doc=parsed&&parsed.Document||parsed,root=doc&&(doc.BkToCstmrStmt||doc.BankToCustomerStatement);if(!root)throw new Error('CAMT053_ROOT_MISSING');
 const statements=arr(root.Stmt);if(!statements.length)throw new Error('CAMT053_STATEMENT_MISSING');const transactions=[],warnings=[];
 statements.forEach((stmt,si)=>arr(stmt&&stmt.Ntry).forEach((ntry,ei)=>{const details=arr(path(ntry,'NtryDtls','TxDtls'));const list=details.length?details:[{}];if(details.length>1&&!details.some(x=>text(txAmt(x)))){warnings.push('aggregate_entry_without_transaction_amounts');list.splice(1)}list.forEach((tx,ti)=>{try{transactions.push(mapCamt(stmt,ntry,tx,ei,ti,hash))}catch(e){warnings.push('statement_'+(si+1)+'_entry_'+(ei+1)+':'+e.message)}})}));
 if(!transactions.length)throw new Error('CAMT053_NO_TRANSACTIONS');return {transactions,warnings,statement_count:statements.length};
}
function mtDate(s){if(!/^\d{6}$/.test(s))return null;const y=Number(s.slice(0,2)),year=y>=70?1900+y:2000+y,out=String(year)+'-'+s.slice(2,4)+'-'+s.slice(4,6);return Number.isNaN(Date.parse(out+'T00:00:00Z'))?null:out}
function marker(raw,key){const m=String(raw||'').match(new RegExp('(?:^|[?\\s])'+key+'[/:]?([^?\\n\\r]+)','i'));return m?clean(m[1],500):''}
export function parseMt940(input,hash=''){
 const value=String(input||'').replace(/\r\n?/g,'\n');if(!value.includes(':61:'))throw new Error('MT940_TRANSACTION_TAG_MISSING');
 let account='',currency='EUR',current=null;const transactions=[],warnings=[],lines=value.split('\n');
 for(let i=0;i<lines.length;i++){const line=lines[i];
  if(line.startsWith(':25:')){account=iban(line.slice(4));continue}
  if(/^:60[FM]:/.test(line)){const m=line.match(/^:60[FM]:[CD]\d{6}([A-Z]{3})/);if(m)currency=m[1];continue}
  if(line.startsWith(':61:')){if(current)transactions.push(current);const m=line.slice(4).trim().match(/^(\d{6})(\d{4})?([RC]?)([DC])([A-Z])?([0-9]+(?:,[0-9]+)?)([A-Z])([A-Z0-9]{3})(.*)$/);if(!m){warnings.push('line_'+(i+1)+':unsupported_61');current=null;continue}const date=mtDate(m[1]),c=parseBankAmountToCents(m[6]);if(!date||c==null){warnings.push('line_'+(i+1)+':invalid_61');current=null;continue}const debit=(m[4]==='D')!==(m[3]==='R'),tail=m[10]||'',parts=tail.split('//'),customer=clean(parts[0].replace(/^N[A-Z0-9]{3}/,''),500),bank=clean(parts[1]||'',500);current={transaction_id:bank||customer||'line-'+(i+1),account_iban:account,counterparty_name:'',counterparty_iban:'',booking_date:date,value_date:date,amount_cents:Math.abs(c)*(debit?-1:1),currency,description:'',end_to_end_id:customer,bank_reference:bank,credit_debit:debit?'debit':'credit',source_format:'mt940',source_file_hash:hash};continue}
  if(line.startsWith(':86:')&&current){let d=line.slice(4);while(i+1<lines.length&&!/^:\d{2}[A-Z]?:/.test(lines[i+1]))d+=' '+lines[++i];current.description=clean(d.replace(/\?\d{2}/g,' '));current.end_to_end_id=marker(d,'EREF')||marker(d,'20')||current.end_to_end_id;current.counterparty_name=marker(d,'NAME')||marker(d,'32');const im=String(d).toUpperCase().match(/\b[A-Z]{2}\d{2}[A-Z0-9]{10,30}\b/);current.counterparty_iban=im?iban(im[0]):''}
 }
 if(current)transactions.push(current);if(!transactions.length)throw new Error('MT940_NO_TRANSACTIONS');return {transactions,warnings,statement_count:1};
}
export function detectBankFormat(text,filename=''){const n=String(filename).toLowerCase(),h=String(text).slice(0,2000);if(n.endsWith('.xml')||/<(?:\w+:)?BkToCstmrStmt\b/.test(h)||/camt\.053/i.test(h))return 'camt053';if(n.endsWith('.sta')||n.endsWith('.940')||h.includes(':61:'))return 'mt940';return null}
export function secureXmlPreflight(text,{maxBytes=5242880,maxDepth=80}={}){const v=String(text||''),errors=[],bytes=new TextEncoder().encode(v).byteLength;if(!bytes)errors.push('XML_EMPTY');if(bytes>maxBytes)errors.push('XML_TOO_LARGE');if(/<!DOCTYPE/i.test(v))errors.push('XML_DOCTYPE_FORBIDDEN');if(/<!ENTITY/i.test(v))errors.push('XML_ENTITY_FORBIDDEN');if(/<\?xml-stylesheet/i.test(v))errors.push('XML_STYLESHEET_FORBIDDEN');let depth=0,peak=0;for(const m of v.matchAll(/<\s*(\/)?([A-Za-z_][\w:.-]*)(?:\s[^<>]*?)?(\/?)\s*>/g)){if(m[1])depth=Math.max(0,depth-1);else if(!m[3]){depth++;peak=Math.max(peak,depth)}if(peak>maxDepth){errors.push('XML_DEPTH_EXCEEDED');break}}return {ok:!errors.length,errors,bytes,maxDepthObserved:peak}}
export async function sha256Hex(input){const b=input instanceof Uint8Array?input:new TextEncoder().encode(String(input||'')),d=await crypto.subtle.digest('SHA-256',b);return Array.from(new Uint8Array(d),x=>x.toString(16).padStart(2,'0')).join('')}
export async function attachTransactionFingerprints(txs,hash){const out=[];for(const t of txs){const key=[t.transaction_id,t.account_iban,t.counterparty_iban,t.booking_date,t.value_date,t.amount_cents,t.currency,t.end_to_end_id,t.bank_reference,clean(t.description).toLowerCase(),t.credit_debit,t.source_format].join('|');out.push({...t,source_file_hash:hash,transaction_fingerprint:await sha256Hex(key)})}return out}
export function statementSummary(txs,warnings=[]){const dates=txs.map(t=>t.booking_date).filter(Boolean).sort(),accounts=[...new Set(txs.map(t=>t.account_iban).filter(Boolean))];return {transaction_count:txs.length,period_start:dates[0]||null,period_end:dates.at(-1)||null,account_iban:accounts.length===1?accounts[0]:null,accounts,credit_total_cents:txs.filter(t=>t.amount_cents>0).reduce((s,t)=>s+t.amount_cents,0),debit_total_cents:txs.filter(t=>t.amount_cents<0).reduce((s,t)=>s+Math.abs(t.amount_cents),0),warnings}}
