function arr(v){return v==null?[]:(Array.isArray(v)?v:[v])}
function text(v){if(v==null)return '';if(typeof v==='string'||typeof v==='number')return String(v).trim();if(typeof v==='object'&&v['#text']!=null)return String(v['#text']).trim();return ''}
function at(v,n){return v&&typeof v==='object'?String(v['@_'+n]||v['@'+n]||''):''}
function path(o,...ks){let v=o;for(const k of ks){if(v==null)return null;v=v[k];if(Array.isArray(v))v=v[0]}return v}
function cents(v){let s=text(v).replace(/\s/g,'');if(!s)return null;let sign=1;if(s[0]==='-'){sign=-1;s=s.slice(1)}if(!/^\d+(?:[.,]\d+)?$/.test(s))return null;const p=s.replace(',','.').split('.'),whole=p[0],frac=p[1]||'';if(whole.length>13)return null;let n=Number(whole)*100+Number((frac+'00').slice(0,2));if(frac.length>2&&Number(frac[2])>=5)n++;return Number.isSafeInteger(n*sign)?n*sign:null}
function amount(v,currency,errors,field){const n=cents(v),ccy=at(v,'currencyID');if(n==null)errors.push({code:'UBL_AMOUNT_INVALID',field,message:field+' is not a valid decimal'});if(ccy&&currency&&ccy!==currency)errors.push({code:'UBL_CURRENCY_MISMATCH',field,message:field+' currency mismatch'});return n}
function partyName(n){return text(path(n,'Party','PartyName','Name'))||text(path(n,'Party','PartyLegalEntity','RegistrationName'))||text(path(n,'Party','PartyIdentification','ID'))}
function endpoint(n){const e=path(n,'Party','EndpointID');return {value:text(e),scheme:at(e,'schemeID')}}
export function ublRoot(parsed){if(parsed&&parsed.Invoice)return {kind:'invoice',document:parsed.Invoice};if(parsed&&parsed.CreditNote)return {kind:'creditnote',document:parsed.CreditNote};if(parsed&&parsed.Document&&parsed.Document.Invoice)return {kind:'invoice',document:parsed.Document.Invoice};if(parsed&&parsed.Document&&parsed.Document.CreditNote)return {kind:'creditnote',document:parsed.Document.CreditNote};return null}
export function validateUblSemantics(parsed,rawXml=''){
 const errors=[],warnings=[],peppolErrors=[],peppolWarnings=[],root=ublRoot(parsed);
 if(!root)return {status:'invalid',errors:[{code:'UBL_ROOT_UNSUPPORTED',field:'root',message:'Expected UBL Invoice or CreditNote'}],warnings,peppol:{status:'invalid',errors:[{code:'PEPPOL_ROOT_UNSUPPORTED',field:'root',message:'Expected UBL Invoice or CreditNote'}],warnings:[]},financial_snapshot:null};
 const d=root.document,isCredit=root.kind==='creditnote',namespaceOk=isCredit?/urn:oasis:names:specification:ubl:schema:xsd:CreditNote-2/.test(rawXml):/urn:oasis:names:specification:ubl:schema:xsd:Invoice-2/.test(rawXml);
 if(!namespaceOk)errors.push({code:'UBL_NAMESPACE',field:'root',message:'UBL 2.x namespace missing or incorrect'});
 const version=text(d.UBLVersionID),id=text(d.ID),issue=text(d.IssueDate),currency=text(d.DocumentCurrencyCode).toUpperCase();
 if(version&&!/^2(?:\.|$)/.test(version))errors.push({code:'UBL_VERSION',field:'UBLVersionID',message:'Only UBL 2.x is supported'});
 if(!id)errors.push({code:'UBL_REQUIRED_ID',field:'ID',message:'Document ID required'});
 if(!/^\d{4}-\d{2}-\d{2}$/.test(issue))errors.push({code:'UBL_REQUIRED_ISSUE_DATE',field:'IssueDate',message:'IssueDate must be YYYY-MM-DD'});
 if(!/^[A-Z]{3}$/.test(currency))errors.push({code:'UBL_REQUIRED_CURRENCY',field:'DocumentCurrencyCode',message:'Three-letter currency required'});
 const supplier=d.AccountingSupplierParty,customer=d.AccountingCustomerParty;if(!partyName(supplier))errors.push({code:'UBL_REQUIRED_SUPPLIER',field:'AccountingSupplierParty',message:'Supplier required'});if(!partyName(customer))errors.push({code:'UBL_REQUIRED_CUSTOMER',field:'AccountingCustomerParty',message:'Customer required'});
 const total=d.LegalMonetaryTotal||{},taxTotal=arr(d.TaxTotal)[0]||{},net=amount(total.TaxExclusiveAmount,currency,errors,'TaxExclusiveAmount'),vat=amount(taxTotal.TaxAmount,currency,errors,'TaxAmount'),gross=amount(total.TaxInclusiveAmount,currency,errors,'TaxInclusiveAmount'),payable=amount(total.PayableAmount,currency,errors,'PayableAmount');
 if(net!=null&&vat!=null&&gross!=null&&Math.abs(net+vat-gross)>1)errors.push({code:'UBL_FINANCIAL_TOTAL_MISMATCH',field:'LegalMonetaryTotal',message:'Net plus VAT must equal gross within one cent'});
 const key=isCredit?'CreditNoteLine':'InvoiceLine',lines=arr(d[key]);if(!lines.length)errors.push({code:'UBL_REQUIRED_LINES',field:key,message:'At least one line required'});let sum=0,all=true;
 lines.forEach((line,i)=>{const a=amount(line.LineExtensionAmount,currency,errors,key+'['+i+'].LineExtensionAmount');if(a==null)all=false;else sum+=a;if(!text(line.ID))errors.push({code:'UBL_LINE_ID',field:key+'['+i+'].ID',message:'Line ID required'});const q=Number(text(isCredit?line.CreditedQuantity:line.InvoicedQuantity));if(!Number.isFinite(q)||q<=0)errors.push({code:'UBL_LINE_QUANTITY',field:key+'['+i+']',message:'Positive quantity required'});if(!text(path(line,'Item','Name'))&&!text(path(line,'Item','Description')))errors.push({code:'UBL_LINE_ITEM',field:key+'['+i+'].Item',message:'Item description required'})});
 if(all&&net!=null&&!arr(d.AllowanceCharge).length&&Math.abs(sum-net)>1)errors.push({code:'UBL_LINE_SUM_MISMATCH',field:key,message:'Line sum must equal net when no document allowance exists'});
 const vatLines=[];for(const sub of arr(taxTotal.TaxSubtotal)){const taxable=amount(sub.TaxableAmount,currency,errors,'TaxSubtotal.TaxableAmount'),v=amount(sub.TaxAmount,currency,errors,'TaxSubtotal.TaxAmount'),rate=Number(text(path(sub,'TaxCategory','Percent'))),category=text(path(sub,'TaxCategory','ID'));if(!Number.isFinite(rate))errors.push({code:'UBL_VAT_RATE',field:'TaxCategory.Percent',message:'VAT rate required'});if(taxable!=null&&v!=null&&Number.isFinite(rate)&&Math.abs(Math.round(taxable*rate/100)-v)>1)errors.push({code:'UBL_VAT_ARITHMETIC',field:'TaxSubtotal',message:'VAT subtotal differs by more than one cent'});vatLines.push({rate:Number.isFinite(rate)?rate:null,category:category||null,taxable_cents:taxable,vat_cents:v})}
 if(!vatLines.length)warnings.push({code:'UBL_VAT_BREAKDOWN_MISSING',field:'TaxSubtotal',message:'VAT breakdown missing'});
 const customization=text(d.CustomizationID),profile=text(d.ProfileID);if(!customization)peppolErrors.push({code:'PEPPOL_CUSTOMIZATION_ID_REQUIRED',field:'CustomizationID',message:'CustomizationID required'});else if(!/peppol|en16931|cen\.eu/i.test(customization))peppolWarnings.push({code:'PEPPOL_CUSTOMIZATION_ID_UNRECOGNIZED',field:'CustomizationID',message:'Unrecognized EN16931/Peppol identifier'});if(!profile)peppolErrors.push({code:'PEPPOL_PROFILE_ID_REQUIRED',field:'ProfileID',message:'ProfileID required'});else if(!/peppol/i.test(profile))peppolWarnings.push({code:'PEPPOL_PROFILE_ID_UNRECOGNIZED',field:'ProfileID',message:'ProfileID not recognized as Peppol'});
 for(const [label,e] of [['supplier',endpoint(supplier)],['customer',endpoint(customer)]]){if(!e.value)peppolErrors.push({code:'PEPPOL_ENDPOINT_REQUIRED',field:label+'.EndpointID',message:label+' EndpointID required'});else if(!e.scheme)peppolErrors.push({code:'PEPPOL_ENDPOINT_SCHEME_REQUIRED',field:label+'.EndpointID',message:label+' endpoint schemeID required'})}
 const snapshot={currency:currency||null,net_cents:net,vat_cents:vat,gross_cents:gross,payable_cents:payable,vat_lines:vatLines,mixed_rates:[...new Set(vatLines.map(x=>x.rate).filter(x=>x!=null))].length>1};
 return {status:errors.length?'invalid':warnings.length?'needs_review':'valid',errors,warnings,peppol:{status:peppolErrors.length?'invalid':peppolWarnings.length?'needs_review':'valid',errors:peppolErrors,warnings:peppolWarnings},financial_snapshot:snapshot,document:{kind:root.kind,id,issue_date:issue,currency,supplier:partyName(supplier),customer:partyName(customer)}};
}
