import test from "node:test";
import assert from "node:assert/strict";
import { overlap, hoursBetween, hardConstraintReasons, scoreEmployee, generateSchedule } from "../src/lib/scheduler-core.mjs";
import { weightedAverage, mean, stddev, forecastRevenue, workloadFromRevenue } from "../src/lib/forecast-core.mjs";
import { shiftHours, shiftCost, labourPercentage } from "../src/lib/labour-core.mjs";
const iso=(d,h,m=0)=>`2026-10-${String(d).padStart(2,"0")}T${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}:00+02:00`;
const baseEmp=(id="e1",extra={})=>({id,name:id,roles:["Bartender"],locationIds:["l1"],skills:["bar"],contractHours:24,desiredHours:24,maxHours:32,hourlyWage:16,experienceLevel:2,availability:[],leave:[],preferences:["evening"],...extra});
const req=(id="r1",extra={})=>({id,role:"Bartender",locationId:"l1",start:iso(10,18),end:iso(10,23),breakMinutes:0,count:1,skills:["bar"],period:"evening",...extra});
test("overlap-identical",()=>assert.equal(overlap(iso(10,18),iso(10,22),iso(10,18),iso(10,22)),true));
test("overlap-partial-left",()=>assert.equal(overlap(iso(10,18),iso(10,22),iso(10,17),iso(10,19)),true));
test("overlap-partial-right",()=>assert.equal(overlap(iso(10,18),iso(10,22),iso(10,21),iso(10,23)),true));
test("overlap-contained",()=>assert.equal(overlap(iso(10,18),iso(10,22),iso(10,19),iso(10,20)),true));
test("overlap-containing",()=>assert.equal(overlap(iso(10,19),iso(10,20),iso(10,18),iso(10,22)),true));
test("overlap-touching-end",()=>assert.equal(overlap(iso(10,18),iso(10,22),iso(10,22),iso(10,23)),false));
test("overlap-touching-start",()=>assert.equal(overlap(iso(10,18),iso(10,22),iso(10,17),iso(10,18)),false));
test("overlap-separate",()=>assert.equal(overlap(iso(10,18),iso(10,22),iso(10,23),iso(11,1)),false));
test("hours-five",()=>assert.equal(hoursBetween(iso(10,18),iso(10,23)),5));
test("hours-break-30",()=>assert.equal(hoursBetween(iso(10,18),iso(10,23),30),4.5));
test("hours-break-60",()=>assert.equal(hoursBetween(iso(10,18),iso(10,23),60),4));
test("hours-negative-clamped",()=>assert.equal(hoursBetween(iso(10,23),iso(10,18)),0));
test("hours-quarter",()=>assert.equal(hoursBetween(iso(10,18),iso(10,18,15)),.25));
test("hours-half",()=>assert.equal(hoursBetween(iso(10,18),iso(10,18,30)),.5));
test("hours-cross-midnight",()=>assert.equal(hoursBetween(iso(10,22),iso(11,4)),6));
test("hours-cross-midnight-break",()=>assert.equal(hoursBetween(iso(10,22),iso(11,4),30),5.5));
test("hours-90min",()=>assert.equal(hoursBetween(iso(10,18),iso(10,19,30)),1.5));
test("hours-break-equals-shift",()=>assert.equal(hoursBetween(iso(10,18),iso(10,19),60),0));
test("hours-break-exceeds-shift",()=>assert.equal(hoursBetween(iso(10,18),iso(10,19),90),0));
test("overlap-cross-midnight",()=>assert.equal(overlap(iso(10,22),iso(11,4),iso(11,3),iso(11,5)),true));
test("eligible-base",()=>assert.equal(scoreEmployee(baseEmp(),req(),{},"balanced").eligible,true));
test("blocked-role",()=>assert.ok(hardConstraintReasons(baseEmp("e1",{roles:["Runner"]}),req(),{}).includes("functie ontbreekt")));
test("blocked-location",()=>assert.ok(hardConstraintReasons(baseEmp("e1",{locationIds:["l2"]}),req(),{}).includes("locatie niet toegestaan")));
test("blocked-skill",()=>assert.ok(hardConstraintReasons(baseEmp("e1",{skills:[]}),req(),{}).some(x=>x.startsWith("ontbrekende skill"))));
test("blocked-overlap",()=>assert.ok(hardConstraintReasons(baseEmp(),req(),{existingAssignments:[{employeeId:"e1",start:iso(10,17),end:iso(10,19)}]}).includes("reeds ingepland")));
test("blocked-max-hours",()=>assert.ok(hardConstraintReasons(baseEmp("e1",{maxHours:25}),req(),{hoursByEmployee:{e1:22}}).includes("maximale uren bereikt")));
test("blocked-leave",()=>assert.ok(hardConstraintReasons(baseEmp("e1",{leave:[{start:iso(10,17),end:iso(10,23)}]}),req(),{}).includes("verlof")));
test("availability-covered",()=>assert.equal(hardConstraintReasons(baseEmp("e1",{availability:[{start:iso(10,17),end:iso(11,1),available:true}]}),req(),{}).length,0));
test("availability-short",()=>assert.ok(hardConstraintReasons(baseEmp("e1",{availability:[{start:iso(10,19),end:iso(10,23),available:true}]}),req(),{}).includes("niet beschikbaar")));
test("availability-false",()=>assert.ok(hardConstraintReasons(baseEmp("e1",{availability:[{start:iso(10,17),end:iso(11,1),available:false}]}),req(),{}).includes("niet beschikbaar")));
test("score-range-balanced",()=>{const s=scoreEmployee(baseEmp(),req(),{},"balanced").score;assert.ok(s>=0&&s<=100)});
test("score-range-cost",()=>{const s=scoreEmployee(baseEmp(),req(),{},"cost").score;assert.ok(s>=0&&s<=100)});
test("score-range-service",()=>{const s=scoreEmployee(baseEmp(),req(),{},"service").score;assert.ok(s>=0&&s<=100)});
test("cost-prefers-cheaper",()=>assert.ok(scoreEmployee(baseEmp("a",{hourlyWage:14}),req(),{},"cost").score>scoreEmployee(baseEmp("b",{hourlyWage:24}),req(),{},"cost").score));
test("service-prefers-experience",()=>assert.ok(scoreEmployee(baseEmp("a",{experienceLevel:4}),req(),{},"service").score>scoreEmployee(baseEmp("b",{experienceLevel:1}),req(),{},"service").score));
test("balanced-prefers-preference",()=>assert.ok(scoreEmployee(baseEmp("a",{preferences:["evening"]}),req(),{},"balanced").score>scoreEmployee(baseEmp("b",{preferences:[]}),req(),{},"balanced").score));
test("fairness-under-hours",()=>assert.ok(scoreEmployee(baseEmp("a",{desiredHours:24}),req(),{hoursByEmployee:{a:20}},"balanced").breakdown.fairness>scoreEmployee(baseEmp("b",{desiredHours:24}),req(),{hoursByEmployee:{b:2}},"balanced").breakdown.fairness));
test("no-skills-required",()=>assert.equal(scoreEmployee(baseEmp("e1",{skills:[]}),req("r",{skills:[]}),{}).breakdown.skillCoverage,100));
test("blocked-score-infinite",()=>assert.equal(scoreEmployee(baseEmp("e1",{roles:[]}),req(),{}).score,-Infinity));
test("explain-available",()=>assert.ok(scoreEmployee(baseEmp(),req(),{}).reasons.includes("beschikbaar")));
test("explain-role",()=>assert.ok(scoreEmployee(baseEmp(),req(),{}).reasons.some(x=>x.startsWith("functie:"))));
test("explain-fairness",()=>assert.ok(scoreEmployee(baseEmp(),req(),{}).reasons.some(x=>x.startsWith("fairness"))));
test("explain-cost",()=>assert.ok(scoreEmployee(baseEmp(),req(),{}).reasons.some(x=>x.startsWith("kostenfit"))));
test("max-hours-exact",()=>assert.equal(hardConstraintReasons(baseEmp("e1",{maxHours:27}),req(),{hoursByEmployee:{e1:22}}).includes("maximale uren bereikt"),false));
test("max-hours-over",()=>assert.equal(hardConstraintReasons(baseEmp("e1",{maxHours:26.9}),req(),{hoursByEmployee:{e1:22}}).includes("maximale uren bereikt"),true));
test("leave-touching-end",()=>assert.equal(hardConstraintReasons(baseEmp("e1",{leave:[{start:iso(10,14),end:iso(10,18)}]}),req(),{}).includes("verlof"),false));
test("existing-touching-start",()=>assert.equal(hardConstraintReasons(baseEmp(),req(),{existingAssignments:[{employeeId:"e1",start:iso(10,12),end:iso(10,18)}]}).includes("reeds ingepland"),false));
test("missing-multiple-skill",()=>assert.ok(hardConstraintReasons(baseEmp("e1",{skills:["bar"]}),req("r",{skills:["bar","wine"]}),{}).join(" ").includes("wine")));
test("service-weight-diff",()=>{const emp=baseEmp("e1",{hourlyWage:24,experienceLevel:4});assert.notEqual(scoreEmployee(emp,req(),{},"service").score,scoreEmployee(emp,req(),{},"cost").score)});
test("deterministic-score",()=>assert.equal(scoreEmployee(baseEmp(),req(),{},"balanced").score,scoreEmployee(baseEmp(),req(),{},"balanced").score));
test("mean-basic",()=>assert.equal(mean([10,20,30]),20));
test("mean-empty",()=>assert.equal(mean([]),0));
test("weighted-single",()=>assert.equal(weightedAverage([100]),100));
test("weighted-trend-up",()=>assert.ok(weightedAverage([100,200,300])>mean([100,200,300])));
test("stddev-zero",()=>assert.equal(stddev([10,10,10]),0));
test("stddev-empty",()=>assert.equal(stddev([]),0));
test("forecast-empty-zero",()=>assert.equal(forecastRevenue([]).forecast,0));
test("forecast-positive",()=>assert.ok(forecastRevenue([100,110,120,130]).forecast>0));
test("forecast-band-order",()=>{const f=forecastRevenue([100,110,120,130]);assert.ok(f.low<=f.forecast&&f.high>=f.forecast)});
test("forecast-confidence-range",()=>{const f=forecastRevenue([100,110,120,130]);assert.ok(f.confidence>=35&&f.confidence<=95)});
test("forecast-adjust-plus",()=>assert.ok(forecastRevenue([100,100,100],10).forecast>forecastRevenue([100,100,100],0).forecast));
test("forecast-adjust-minus",()=>assert.ok(forecastRevenue([100,100,100],-10).forecast<forecastRevenue([100,100,100],0).forecast));
test("forecast-ignore-negative",()=>assert.equal(forecastRevenue([-100,100]).forecast,100));
test("forecast-ignore-nan",()=>assert.equal(forecastRevenue([100,Number.NaN]).forecast,100));
test("forecast-six-pct-min-margin",()=>{const f=forecastRevenue([100,100,100]);assert.ok(f.high-f.forecast>=6)});
test("workload-basic",()=>assert.equal(workloadFromRevenue(950,{revenuePerLabourHour:95}).totalLabourHours,10));
test("workload-round-half",()=>assert.equal(workloadFromRevenue(1000,{revenuePerLabourHour:95}).totalLabourHours,11));
test("workload-zero",()=>assert.equal(workloadFromRevenue(0,{revenuePerLabourHour:95}).totalLabourHours,0));
test("workload-invalid-ratio",()=>assert.equal(workloadFromRevenue(1000,{revenuePerLabourHour:0}).totalLabourHours,0));
test("forecast-factors-present",()=>assert.ok(forecastRevenue([100,110]).factors.length>=2));
test("shift-hours-basic",()=>assert.equal(shiftHours(iso(10,18),iso(10,23)),5));
test("shift-hours-break",()=>assert.equal(shiftHours(iso(10,18),iso(10,23),30),4.5));
test("shift-hours-overnight",()=>assert.equal(shiftHours(iso(10,22),iso(11,4)),6));
test("cost-base",()=>assert.equal(shiftCost({start:iso(10,18),end:iso(10,23),hourlyWage:10,employerFactor:1}),50));
test("cost-employer-factor",()=>assert.equal(shiftCost({start:iso(10,18),end:iso(10,23),hourlyWage:10,employerFactor:1.2}),60));
test("cost-surcharge",()=>assert.equal(shiftCost({start:iso(10,18),end:iso(10,23),hourlyWage:10,employerFactor:1,surchargePct:20}),60));
test("cost-break",()=>assert.equal(shiftCost({start:iso(10,18),end:iso(10,23),breakMinutes:60,hourlyWage:10,employerFactor:1}),40));
test("cost-rounding",()=>assert.equal(shiftCost({start:iso(10,18),end:iso(10,19),hourlyWage:10.555,employerFactor:1}),10.56));
test("labour-pct-basic",()=>assert.equal(labourPercentage(250,1000),25));
test("labour-pct-decimal",()=>assert.equal(labourPercentage(263.5,1000),26.4));
test("labour-pct-zero-revenue",()=>assert.equal(labourPercentage(100,0),null));
test("labour-pct-over-100",()=>assert.equal(labourPercentage(1200,1000),120));
test("cost-zero-wage",()=>assert.equal(shiftCost({start:iso(10,18),end:iso(10,23),hourlyWage:0}),0));
test("cost-zero-hours",()=>assert.equal(shiftCost({start:iso(10,18),end:iso(10,18),hourlyWage:20}),0));
test("shift-negative-clamped",()=>assert.equal(shiftHours(iso(10,23),iso(10,18)),0));
test("schedule-one",()=>assert.equal(generateSchedule([req()],[baseEmp()]).assignments.length,1));
test("schedule-count-two",()=>assert.equal(generateSchedule([req("r",{count:2})],[baseEmp("a"),baseEmp("b")]).assignments.length,2));
test("schedule-unfilled-no-emp",()=>assert.equal(generateSchedule([req()],[]).unfilled.length,1));
test("schedule-unfilled-wrong-role",()=>assert.equal(generateSchedule([req()],[baseEmp("a",{roles:["Runner"]})]).unfilled.length,1));
test("schedule-prefers-cheap-cost",()=>assert.equal(generateSchedule([req()],[baseEmp("a",{hourlyWage:14}),baseEmp("b",{hourlyWage:30})],"cost").assignments[0].employeeId,"a"));
test("schedule-prefers-experience-service",()=>assert.equal(generateSchedule([req()],[baseEmp("a",{experienceLevel:1}),baseEmp("b",{experienceLevel:4})],"service").assignments[0].employeeId,"b"));
test("schedule-avoids-overlap-second-slot",()=>{const g=generateSchedule([req("r",{count:2})],[baseEmp("a"),baseEmp("b")]);assert.notEqual(g.assignments[0].employeeId,g.assignments[1].employeeId)});
test("schedule-deterministic-tie",()=>assert.equal(generateSchedule([req()],[baseEmp("b"),baseEmp("a")]).assignments[0].employeeId,"a"));
test("schedule-hours-updated",()=>assert.equal(generateSchedule([req()],[baseEmp("a")]).hoursByEmployee.a,5));
test("schedule-strategy-label",()=>assert.equal(generateSchedule([req()],[baseEmp("a")],"service").strategy,"service"));
test("schedule-reason-present",()=>assert.ok(generateSchedule([req()],[baseEmp("a")]).assignments[0].reasons.length>0));
test("schedule-breakdown-present",()=>assert.equal(typeof generateSchedule([req()],[baseEmp("a")]).assignments[0].breakdown.fairness,"number"));
test("schedule-two-nonoverlap-same-emp",()=>assert.equal(generateSchedule([req("r1",{start:iso(10,12),end:iso(10,16)}),req("r2",{start:iso(10,18),end:iso(10,22)})],[baseEmp("a",{maxHours:40})]).assignments.length,2));
test("schedule-max-hours-causes-unfilled",()=>assert.equal(generateSchedule([req("r1",{start:iso(10,12),end:iso(10,17)}),req("r2",{start:iso(10,18),end:iso(10,23)})],[baseEmp("a",{maxHours:5})]).unfilled.length,1));
test("schedule-no-crash-impossible",()=>assert.doesNotThrow(()=>generateSchedule([req("r",{count:5})],[baseEmp("a")]));
