import assert from 'node:assert/strict';
import {loadApp,financialNames} from './production-code.mjs';
const c=loadApp(['processorAnalysisToCandidate','expenseTaxTreatment','expenseVat','expenseGross','expenseDeductibleVat','toCents','fromCents','roundMoney'],{ibanValid:()=>false});
const raw={documentType:'purchase_invoice',supplier:{name:'Foreign Test'},invoice:{invoiceNumber:'BE-1'},amounts:{subtotal:1350,vatTotal:270,total:1620,detectedVatRates:[20],accountingVatTreatment:'review_required',advancePayment:300,outstandingAmount:1320},confidence:{vatRates:.9},processing:{reviewRouting:{mode:'FULL_REVIEW',fields:['vatRates']}}};
const d=c.processorAnalysisToCandidate(raw,'');
assert.equal(d.vatRate,20);
assert.equal(d.advancePayment,300);
assert.equal(d.outstandingAmount,1320);
assert.equal(d.accountingVatTreatment,'review_required');
assert.equal(c.expenseVat({exVat:1350,vatAmount:270,gross:1620,taxTreatment:'foreign'}),270);
assert.equal(c.expenseDeductibleVat({exVat:1350,vatAmount:270,gross:1620,taxTreatment:'foreign'}),0);
assert.equal(c.expenseGross({exVat:1350,vatAmount:270,gross:1620,taxTreatment:'foreign'}),1620);
assert.equal(c.expenseDeductibleVat({exVat:100,vatAmount:21,gross:121}),21);
console.log('V4.1 adapter and foreign accounting separation: PASS');
const merged=loadApp(['mergeAIParsed','normalizeAiCandidate'],{ibanValid:()=>false,scoreParsedInvoice:()=>50});
const candidate=merged.mergeAIParsed({type:'purchase'},d);
assert.equal(candidate.advancePayment,300,'full parsing pipeline must preserve payment semantics');
assert.equal(candidate.accountingVatTreatment,'review_required');
console.log('V4 full parser merge contract: PASS');
// The processor leaves the supplier empty when it is not sure (for example when the only
// name it sees is the user's own company). The browser text guess must not refill it.
const unsure=c.processorAnalysisToCandidate({documentType:'purchase_invoice',supplier:{name:null,kvk:null},customer:{name:'Kwinest'},invoice:{invoiceNumber:'CB-2026-184'},amounts:{total:249.99},confidence:{supplierName:.15},processing:{reviewRouting:{mode:'FULL_REVIEW',fields:['supplierName']}}},'');
const ownGuess=merged.mergeAIParsed({type:'purchase',party:'Kwinest',kvk:'11223344',address:'Teststraat 1'},unsure);
assert.equal(ownGuess.party,'','an empty processor supplier stays empty for review');
assert.equal(ownGuess.kvk,'','no own KvK under an unknown supplier');
const sure=merged.mergeAIParsed({type:'purchase',party:'Kwinest'},c.processorAnalysisToCandidate({documentType:'purchase_invoice',supplier:{name:'Coolblue B.V.',kvk:'24304000'},customer:{name:'Kwinest'},amounts:{total:249.99},confidence:{supplierName:.97}},''));
assert.equal(sure.party,'Coolblue B.V.');
assert.equal(sure.kvk,'24304000');
console.log('Processor supplier role is authoritative in merge: PASS');
const vat=loadApp(['trustedVatLinesForImport','canonicalFinancialVatLines','financialMoneyCents','roundMoney','toCents','fromCents']);
const mixedCredit=vat.trustedVatLinesForImport({isCredit:true,mixedRates:true,vatLines:[{rate:9,taxableAmount:-100,vatAmount:-9},{rate:21,taxableAmount:-100,vatAmount:-21}]},200,30,null);
assert.equal(mixedCredit.ok,true,'signed mixed credit must remain saveable');

const foreignExpense={id:'foreign',date:'2026-10-03',vendor:'Foreign Test',invoiceNumber:'BE-1',category:'Software',exVat:1350,vatAmount:270,gross:1620,taxTreatment:'foreign'};
const accounting=loadApp([...financialNames,'expenseDeductibleVat','expenseAccountingCost','quarterVatPosition','buildReportPreview','generatedJournal','expenseLedgerAccount','expenseCounterAccount','addSignedLine','jl','journalEntry','validateJournalEntry'],{state:{company:{},invoices:[],expenses:[foreignExpense],transactions:[]},currentQuarter:()=>4,currentBookYear:()=>2026,inQuarter:()=>true,reportRange:()=>({from:'2026-10-01',to:'2026-12-31'}),inRange:()=>true,money:v=>Number(v).toFixed(2),dateNL:v=>v,esc:v=>String(v??''),getContact:()=>({name:''}),LEDGER_ACCOUNT_NAMES:{},console});
assert.equal(accounting.quarterVatPosition(),0);
const report=accounting.buildReportPreview();
assert.match(report,/<span>Kosten[^<]*<\/span><b>1620.00<\/b>/);
assert.match(report,/<span>Btw op kosten<\/span><b>− 0.00<\/b>/);
const entry=accounting.generatedJournal()[0];
assert.equal(entry.lines.some(l=>l.account==='1530'),false);
assert.equal(entry.lines.find(l=>l.account==='4530').debit,1620);
assert.equal(accounting.validateJournalEntry(entry).ok,true);
const mixed=c.processorAnalysisToCandidate({...raw,amounts:{...raw.amounts,detectedVatRates:[9,20],vatLines:[{rate:9,taxableAmount:100,vatAmount:9}]}});
assert.equal(mixed.mixedRates,true,'partially extracted foreign mixed VAT must never become a single-rate document');
console.log('Foreign VAT report, reserve, balanced journal and mixed adapter: PASS');
