import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {webcrypto} from 'node:crypto';
const context={crypto:webcrypto,TextEncoder,console};context.globalThis=context;
const file=new URL('../public/assets/document-intelligence.js',import.meta.url);
assert.ok(fs.existsSync(file),'Document intelligence learning module must exist');
vm.runInNewContext(fs.readFileSync(file,'utf8'),context);
const I=context.BoekunaDocumentIntelligence;
const a={ownerId:'a',profiles:{},feedback:[]},b={ownerId:'b',profiles:{},feedback:[]};
const d={party:'Test Supplier',vatId:'NL123456789B01',currency:'EUR',vatRate:21,category:'Software',invoiceNumber:'INV-1',net:100,vatAmount:21,gross:121,issueDate:'2026-10-01',documentType:'purchase_invoice',fieldConfidence:{party:96,invoiceNumber:96,issueDate:96,net:99,vatAmount:99,gross:99,vatRate:96}};
await I.recordFeedback(a,'a',d,{...d,invoiceNumber:'CORRECTED'},'sha-1');
assert.equal(a.feedback.length,1);
await I.recordFeedback(a,'a',d,{...d,invoiceNumber:'CORRECTED'},'sha-1');
assert.equal(a.feedback.length,1,'Reopening same document does not multiply observations');
assert.equal(Object.keys(b.profiles).length,0);
await assert.rejects(I.recordFeedback(a,'b',d,d,'sha-2'),/owner/);
assert.ok(!JSON.stringify(a).includes('Test Supplier'));
assert.ok(!JSON.stringify(a).includes('CORRECTED'));
assert.ok(!JSON.stringify(a).includes('NL123456789B01'));
console.log('V4.1 tenant-local correction feedback: PASS');
