import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {webcrypto} from 'node:crypto';
const context={crypto:webcrypto,TextEncoder,console};context.globalThis=context;
const file=new URL('../public/assets/document-intelligence.js',import.meta.url);
assert.ok(fs.existsSync(file),'Document intelligence learning module must exist');
vm.runInNewContext(fs.readFileSync(file,'utf8'),context);
const I=context.BoekunaDocumentIntelligence;
const a={ownerId:'a',profiles:{},feedback:[]},b={ownerId:'b',profiles:{},feedback:[]};
const d={party:'Test Supplier',vatId:'NL123456789B01',currency:'EUR',vatRate:21,category:'Software',invoiceNumber:'INV-1',net:100,vatAmount:21,gross:121,issueDate:'2026-10-01',documentType:'purchase_invoice',fieldConfidence:{documentType:96,party:96,invoiceNumber:96,issueDate:96,net:99,vatAmount:99,gross:99,vatRate:96}};
await I.recordFeedback(a,'a',d,{...d,invoiceNumber:'CORRECTED'},'sha-1');
assert.equal(a.feedback.length,1);
await I.recordFeedback(a,'a',d,{...d,invoiceNumber:'CORRECTED'},'sha-1');
assert.equal(a.feedback.length,1,'Reopening same document does not multiply observations');
assert.equal(Object.keys(b.profiles).length,0);
await assert.rejects(I.recordFeedback(a,'b',d,d,'sha-2'),/owner/);
assert.ok(!JSON.stringify(a).includes('Test Supplier'));
assert.ok(!JSON.stringify(a).includes('CORRECTED'));
assert.ok(!JSON.stringify(a).includes('NL123456789B01'));
console.log('V4.1 tenant-local correction feedback: PASS');
const memory=I.create('a');memory.enabled=true;
const weak={...d,fieldConfidence:{...d.fieldConfidence,party:78,invoiceNumber:78,issueDate:78,vatRate:78}};
const before=I.reviewRoute(weak);
assert.equal(before.mode,'FULL_REVIEW');
for(let n=0;n<30;n++){const current={...weak,invoiceNumber:'INV-'+n};await I.recordFeedback(memory,'a',current,current,'unique-'+n)}
const enriched=await I.predict(memory,'a',weak);
assert.equal(enriched.reviewRouting.mode,'QUICK_REVIEW','repeat supplier reduces review only after calibrated history');
assert.equal(enriched.gross,121);assert.equal(enriched.net,100);assert.equal(enriched.vatRate,21);
assert.equal(enriched.invoiceNumber,'INV-1','memory never invents invoice number');
assert.ok(enriched.memoryEvidence.every(x=>x.source==='tenant-confirmations'&&x.observations>=3));
const manual=await I.predict(memory,'a',{...weak,category:'Marketing',fieldProvenance:{category:{source:'user',confirmed:true}}});
assert.equal(manual.category,'Marketing','user confirmed always wins');
const shadow=I.create('a');shadow.profiles=memory.profiles;shadow.feedback=memory.feedback;
const shadowResult=await I.predict(shadow,'a',weak);
assert.equal(shadowResult.reviewRouting.mode,before.mode,'shadow mode does not change routing');
assert.equal(shadowResult.memoryShadow.mode,'QUICK_REVIEW');
const bad=await I.predict(memory,'a',{...weak,anomalyCodes:['VAT_MATH_MISMATCH']});
assert.equal(bad.reviewRouting.mode,'FULL_REVIEW');
const foreign=await I.predict(memory,'a',{...d,accountingVatTreatment:'review_required'});
assert.equal(foreign.reviewRouting.mode,'FULL_REVIEW');
const noHistory=await I.predict(b,'b',weak);
assert.equal(noHistory.reviewRouting.mode,'FULL_REVIEW');
const metric=I.telemetry({...d,anomalyCodes:['VAT_MATH_MISMATCH']});
for(const value of ['Test Supplier','INV-1','121','123456789'])assert.ok(!JSON.stringify(metric).includes(value));
assert.ok(!Object.hasOwn(metric,'gross'));
assert.equal(I.relationshipCandidates({...d,isCredit:true,referencedInvoiceNumber:'OLD-1'},[{id:'original',...d,invoiceNumber:'OLD-1'}])[0].id,'original');
assert.equal(I.relationshipCandidates({...d,isCredit:true,referencedInvoiceNumber:'OLD-1'},[{id:'other',...d,party:'Other Supplier',invoiceNumber:'OLD-1'}]).length,0);
const allHigh={...d,fieldConfidence:{...d.fieldConfidence,currency:96}};
assert.equal(I.reviewRoute(allHigh,true).mode,'AUTO_ACCEPT_CANDIDATE');
assert.equal(I.reviewRoute({...allHigh,fieldConfidence:{...allHigh.fieldConfidence,documentType:60}},true).mode,'QUICK_REVIEW','uncertain type prevents auto-accept');
assert.equal(I.reviewRoute(allHigh,true).autoBook,false);
const aggregate=I.aggregateMetrics(a);
assert.equal(aggregate.correctedDocuments,1);assert.equal(aggregate.fields.invoiceNumber.corrections,1);
assert.ok(!JSON.stringify(aggregate).includes('CORRECTED'));
const retained=I.create('a');await I.recordFeedback(retained,'a',d,d,'retention-test');
I.cleanup(retained,Date.now()+181*86400000);assert.equal(retained.feedback.length,0);assert.equal(Object.keys(retained.profiles).length,0);
const rejecting=I.create('a');rejecting.enabled=true;
for(let n=0;n<30;n++)await I.recordFeedback(rejecting,'a',weak,weak,'accepted-'+n);
await I.recordFeedback(rejecting,'a',weak,weak,'rejected-one','rejected');
assert.equal((await I.predict(rejecting,'a',weak)).memoryEvidence.length,0,'rejection suppresses ranking');
assert.equal(I.confidenceEstimate({observations:30,correct:20}),65,'poor outcomes cannot gain high confidence');
assert.ok(I.telemetry({...d,anomalyCodes:['LINE_VAT_MISMATCH','PII']}).anomalyTypes.includes('LINE_VAT_MISMATCH'));
const unusual=await I.predict(memory,'a',{...weak,gross:12100,net:10000,vatAmount:2100});
assert.equal(unusual.reviewRouting.mode,'FULL_REVIEW','large amount band change prompts review without changing money');
assert.equal(unusual.gross,12100);assert.ok(unusual.memoryAnomalyFields.includes('gross'));
const payment={...d,type:'payment',invoiceDate:d.issueDate,total:d.gross,paymentReference:'PAY-1'};
assert.equal(I.relationshipCandidates({...d,paymentReference:'PAY-1'},[payment])[0].type,'payment_for');
assert.equal(I.relationshipCandidates({...d,paymentReference:'PAY-1'},[{...payment,total:122}]).length,0);
I.forget(memory,'a');assert.equal(Object.keys(memory.profiles).length,0);assert.equal(memory.feedback.length,0);
console.log('V4.3 calibrated prediction, shadow routing, privacy and cross-document evidence: PASS');

assert.equal(I.telemetry({...d,reviewRouting:{mode:"FULL_REVIEW"},anomalyCodes:["PRINTED_SUBTOTAL_CONFLICT"],confidenceScore:.95}).reviewMode,"FULL_REVIEW");
assert.equal(I.telemetry({...d,reviewRouting:{mode:"AUTO_ACCEPT_CANDIDATE"}}).reviewMode,"AUTO_ACCEPT_CANDIDATE");
assert.deepEqual(I.telemetry({...d,anomalyCodes:["PRINTED_VAT_TOTAL_CONFLICT","PII"]}).anomalyTypes,["PRINTED_VAT_TOTAL_CONFLICT"]);
