import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';

const root=process.cwd();
const build=spawnSync(process.execPath,['scripts/build-marketing.mjs'],{cwd:root,encoding:'utf8'});
assert.equal(build.status,0,'Marketing build failed: '+(build.stderr||build.stdout));
const dist=path.join(root,'dist','marketing');
const home=fs.readFileSync(path.join(dist,'index.html'),'utf8');
assert.ok(home.includes('Nieuwe website in ontwikkeling.'),'Clean holding copy missing');
assert.match(home,/<meta name="robots" content="noindex,follow">/i);
assert.equal(/<img\b/i.test(home),false,'Holding page must not use marketing images');
assert.equal(/<script\b/i.test(home),false,'Holding page must not use marketing JS');
for(const token of ['editorial-hero','project-grid','editorial-pricing','audience-grid','product-marquee'])assert.equal(home.includes(token),false,'Old presentation returned: '+token);
for(const old of ['assets/stories','assets/product','assets/marketing-people','assets/site.css','assets/site.js','assets/editorial-marketing.css','assets/premium-marketing.css','assets/onepage.css','assets/marketing.js'])assert.equal(fs.existsSync(path.join(dist,old)),false,'Old public marketing asset returned: '+old);
const css=fs.readFileSync(path.join(dist,'assets','baseline.css'),'utf8');
for(const token of ['#1B1F23','#63D471','#F6F7F8','#8A949C','#FFFFFF'])assert.ok(css.includes(token),'Canonical BOEKUNA token missing '+token);
assert.equal(css.includes('#E7FE55'),false,'Retired lime token returned');
assert.equal(css.includes('#BFE7EC'),false,'Retired cyan token returned');
console.log('Marketing clean-slate asset QA: PASS (no old site imagery/runtime; canonical baseline only)');
