import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createClient} from "npm:@supabase/supabase-js@2";
import {XMLParser,XMLValidator} from "npm:fast-xml-parser@5.11.1";
import {validateXsd} from "npm:peppol-validator@0.1.0";
import {validateIban,validateBic,analyzeOcrIban} from "./lib/iban-bic.mjs";
import {detectBankFormat,secureXmlPreflight,parseCamt053,parseMt940,sha256Hex as bankSha,attachTransactionFingerprints,statementSummary} from "./lib/bank-import.mjs";
import {matchTransactionAgainstLedger,invoiceOutstandingCents} from "./lib/matching.mjs";
import {sha256Hex as docSha,textFingerprint,supplierFingerprint,normalizeDuplicateFingerprint,findDuplicateCandidates} from "./lib/duplicates.mjs";
import {validateUblSemantics} from "./lib/ubl.mjs";

const URL=Deno.env.get("SUPABASE_URL")!,ANON=Deno.env.get("SUPABASE_ANON_KEY")!,SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const admin=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});
const ENABLED=Deno.env.get("FINANCIAL_AUTOMATION_ENABLED")!=="false",MAX_BODY=6*1024*1024,MAX_BANK=5*1024*1024,MAX_UBL=2*1024*1024,MAX_TX=5000,MAX_MATCH=500;
const ORIGINS=new Set(["https://boekuna-boekhouding.onrender.com","https://kwinest-boekhouding.onrender.com","https://boekuna-qa-staging.onrender.com","https://boekuna.nl","https://www.boekuna.nl","http://localhost:3000","http://127.0.0.1:3000"]);
const LIMITS:any={iban_validate:300,bank_preview:60,bank_commit:20,match_suggest:120,match_confirm:240,duplicate_check:120,duplicate_register:120,ubl_validate:60,ubl_validate_store:30};
function cors(req:Request){const o=req.headers.get("origin")||"";return {"access-control-allow-origin":ORIGINS.has(o)?o:"https://boekuna-boekhouding.onrender.com","access-control-allow-methods":"POST,OPTIONS","access-control-allow-headers":"authorization,apikey,content-type","vary":"Origin"}}
function out(req:Request,body:any,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors(req),"content-type":"application/json","cache-control":"no-store"}})}
function safe(v:any,n=240){return String(v??"").slice(0,n)}
function fail(req:Request,code:string,status:number,ref:string){return out(req,{ok:false,error:{code,reference_id:ref}},status)}
function log(action:string,fields:any={}){console.info("financial_automation",{action,...fields})}
async function body(req:Request){const declared=Number(req.headers.get("content-length")||0);if(declared>MAX_BODY)throw new Error("REQUEST_TOO_LARGE");const t=await req.text();if(new TextEncoder().encode(t).byteLength>MAX_BODY)throw new Error("REQUEST_TOO_LARGE");try{return JSON.parse(t||"{}")}catch{throw new Error("INVALID_JSON")}}
async function auth(req:Request){const h=req.headers.get("Authorization")||"";if(!h.startsWith("Bearer "))return null;const userClient=createClient(URL,ANON,{global:{headers:{Authorization:h}},auth:{persistSession:false,autoRefreshToken:false}});const {data,error}=await userClient.auth.getUser();if(error||!data.user)return null;return {user:data.user,userClient}}
async function canOperate(sb:any){const {data,error}=await sb.rpc("can_operate_bookkeeping");if(error)throw new Error("ENTITLEMENT_CHECK_FAILED");return data===true}
async function rate(userId:string,action:string){const {data,error}=await admin.rpc("consume_financial_automation_rate_limit",{p_user_id:userId,p_action:action,p_limit:LIMITS[action]});if(error)throw new Error("RATE_LIMIT_UNAVAILABLE");if(data!==true)throw new Error("RATE_LIMITED")}
function parser(){return new XMLParser({ignoreAttributes:false,attributeNamePrefix:"@_",removeNSPrefix:true,processEntities:false,trimValues:true,parseTagValue:false,parseAttributeValue:false})}
function xmlErrors(v:any){if(v===true)return [];const e=v&&v.err||v||{};return [{code:"XML_NOT_WELL_FORMED",line:Number(e.line||0)||null,col:Number(e.col||0)||null,message:safe(e.msg||"Invalid XML",300)}]}
async function parseBank(content:string,filename:string){const bytes=new TextEncoder().encode(content).byteLength;if(bytes>MAX_BANK)throw new Error("BANK_FILE_TOO_LARGE");const hash=await bankSha(content),format=detectBankFormat(content,filename);if(!format)throw new Error("BANK_FORMAT_UNSUPPORTED");let parsed:any;if(format==="camt053"){const guard=secureXmlPreflight(content,{maxBytes:MAX_BANK,maxDepth:80});if(!guard.ok)throw new Error(guard.errors[0]);const wf=XMLValidator.validate(content);if(wf!==true)throw new Error("BANK_XML_INVALID");parsed=parseCamt053(parser().parse(content),hash)}else parsed=parseMt940(content,hash);if(parsed.transactions.length>MAX_TX)throw new Error("BANK_TOO_MANY_TRANSACTIONS");parsed.transactions=await attachTransactionFingerprints(parsed.transactions,hash);return {hash,format,...parsed,summary:statementSummary(parsed.transactions,parsed.warnings||[])}}
async function existingTx(userId:string,prints:string[]){const found=new Set<string>();for(let i=0;i<prints.length;i+=500){const {data,error}=await admin.from("bank_transactions").select("transaction_fingerprint").eq("user_id",userId).in("transaction_fingerprint",prints.slice(i,i+500));if(error)throw error;for(const r of data||[])found.add(r.transaction_fingerprint)}return found}
async function bankPreview(userId:string,b:any){const p=await parseBank(safe(b.content,MAX_BANK+1000),safe(b.filename,200));const {data:old,error}=await admin.from("bank_imports").select("id").eq("user_id",userId).eq("source_file_hash",p.hash).maybeSingle();if(error)throw error;const dup=await existingTx(userId,p.transactions.map((t:any)=>t.transaction_fingerprint));return {source_format:p.format,source_file_hash:p.hash,file_duplicate:!!old,duplicate_transactions:p.transactions.filter((t:any)=>dup.has(t.transaction_fingerprint)).map((t:any)=>t.transaction_fingerprint),summary:p.summary,transactions:p.transactions,warnings:p.warnings}}
async function bankCommit(userId:string,b:any){const p=await bankPreview(userId,b);if(p.file_duplicate)throw new Error("BANK_FILE_ALREADY_IMPORTED");const dup=new Set(p.duplicate_transactions),fresh=p.transactions.filter((t:any)=>!dup.has(t.transaction_fingerprint)),s=p.summary;const importRow={source_format:p.source_format,source_file_hash:p.source_file_hash,source_name:safe(b.filename,200)||null,account_iban:s.account_iban,period_start:s.period_start,period_end:s.period_end,transaction_count:p.transactions.length,credit_total_cents:s.credit_total_cents,debit_total_cents:s.debit_total_cents,duplicate_count:p.transactions.length-fresh.length,warning_count:(p.warnings||[]).length};const rows=fresh.map((t:any)=>({transaction_id:safe(t.transaction_id,500)||null,account_iban:safe(t.account_iban,64)||null,counterparty_name:safe(t.counterparty_name,500)||null,counterparty_iban:safe(t.counterparty_iban,64)||null,booking_date:t.booking_date,value_date:t.value_date,amount_cents:t.amount_cents,currency:t.currency,description:safe(t.description,2000),end_to_end_id:safe(t.end_to_end_id,500)||null,bank_reference:safe(t.bank_reference,500)||null,credit_debit:t.credit_debit,source_format:t.source_format,source_file_hash:t.source_file_hash,transaction_fingerprint:t.transaction_fingerprint}));const {data:importId,error:commitError}=await admin.rpc("commit_financial_bank_import",{p_user_id:userId,p_import:importRow,p_transactions:rows});if(commitError)throw commitError;const {data:inserted,error:readError}=await admin.from("bank_transactions").select("id,transaction_id,booking_date,value_date,amount_cents,currency,description,counterparty_name,counterparty_iban,end_to_end_id,bank_reference,credit_debit,status,transaction_fingerprint").eq("user_id",userId).eq("bank_import_id",importId).order("booking_date",{ascending:true});if(readError)throw readError;return {import_id:importId,source_format:p.source_format,summary:{...p.summary,duplicate_count:p.transactions.length-fresh.length},warnings:p.warnings,transactions:inserted||[]}}
async function ledger(userId:string,sb:any){const {data,error}=await sb.from("ledger_state").select("state,version").eq("user_id",userId).single();if(error)throw error;return data}
async function suggestions(userId:string,sb:any,b:any){const l=await ledger(userId,sb);let q=admin.from("bank_transactions").select("id,transaction_id,booking_date,value_date,amount_cents,currency,description,counterparty_name,counterparty_iban,end_to_end_id,bank_reference,credit_debit,status,transaction_fingerprint").eq("user_id",userId).neq("status","matched").order("booking_date",{ascending:false}).limit(MAX_MATCH);const ids=Array.isArray(b.transaction_ids)?b.transaction_ids.slice(0,MAX_MATCH).map(String):[];if(ids.length)q=q.in("id",ids);const {data,error}=await q;if(error)throw error;const results=[];for(const tx of data||[]){const m=matchTransactionAgainstLedger(tx,l.state);if(m.best){const persisted=m.state==="exact/high-confidence"?"suggested":m.state;const {error:e}=await admin.from("transaction_matches").upsert({user_id:userId,bank_transaction_id:tx.id,target_type:m.best.target_type,target_ref:m.best.target_ref,state:m.state,score:m.score,evidence:m.best.evidence},{onConflict:"user_id,bank_transaction_id,target_type,target_ref"});if(e)throw e;await admin.from("bank_transactions").update({status:persisted}).eq("id",tx.id).eq("user_id",userId)}results.push({transaction_id:tx.id,...m})}return {ledger_version:l.version,results}}
function nextLedger(state:any,tx:any,targetType:string,targetRef:string,manualPaymentId=""){const next=structuredClone(state||{});if(!Array.isArray(next.transactions))next.transactions=[];const mirror={id:"bank-"+tx.id,serverTransactionId:tx.id,sourceFingerprint:tx.transaction_fingerprint,date:tx.booking_date,amount:Number(tx.amount_cents)/100,amount_cents:Number(tx.amount_cents),description:tx.description||"",counterparty:tx.counterparty_name||"",status:"matched",matchType:targetType,matchId:targetRef};const idx=next.transactions.findIndex((t:any)=>t&&t.serverTransactionId===tx.id);if(idx>=0)next.transactions[idx]={...next.transactions[idx],...mirror};else next.transactions.push(mirror);if(targetType==="invoice"){const i=(next.invoices||[]).find((x:any)=>String(x.id)===targetRef);if(!i)throw new Error("MATCH_INVOICE_NOT_FOUND");if(manualPaymentId){const payments=Array.isArray(i.payments)?i.payments:[],payment=payments.find((p:any)=>String(p&&p.id)===manualPaymentId);if(!payment)throw new Error("MANUAL_PAYMENT_NOT_FOUND");payment.bankTransactionId=tx.id;payment.bankTransactionFingerprint=tx.transaction_fingerprint}const outstanding=invoiceOutstandingCents(i,next.transactions);i.status=outstanding<=2?"paid":i.status==="paid"?"sent":i.status}else if(manualPaymentId)throw new Error("INVALID_MANUAL_PAYMENT_LINK");if(targetType==="expense"&&!(next.expenses||[]).some((x:any)=>String(x.id)===targetRef))throw new Error("MATCH_EXPENSE_NOT_FOUND");return next}
async function confirm(userId:string,sb:any,b:any){const txId=safe(b.transaction_id,80),targetType=safe(b.target_type,20),targetRef=safe(b.target_ref,240),manualPaymentId=safe(b.manual_payment_id,120);if(!txId||!["invoice","expense"].includes(targetType)||!targetRef)throw new Error("INVALID_MATCH_TARGET");if(manualPaymentId&&targetType!=="invoice")throw new Error("INVALID_MANUAL_PAYMENT_LINK");const {data:tx,error}=await admin.from("bank_transactions").select("*").eq("id",txId).eq("user_id",userId).single();if(error)throw error;if(tx.status==="matched")throw new Error("MATCH_ALREADY_CONFIRMED");const l=await ledger(userId,sb),m=matchTransactionAgainstLedger(tx,l.state),selected=(m.candidates||[]).find((x:any)=>x.target_type===targetType&&x.target_ref===targetRef),score=selected?selected.score:0,evidence=selected?selected.evidence:["manual_user_override"],next=nextLedger(l.state,tx,targetType,targetRef,manualPaymentId);const {data:newVersion,error:rpc}=await admin.rpc("commit_financial_bank_match",{p_user_id:userId,p_expected_version:l.version,p_state:next,p_bank_transaction_id:tx.id,p_target_type:targetType,p_target_ref:targetRef,p_score:score,p_evidence:evidence});if(rpc)throw rpc;if(newVersion==null)throw new Error("LEDGER_VERSION_CONFLICT");return {transaction_id:tx.id,target_type:targetType,target_ref:targetRef,state:"manually_matched",score,evidence,ledger_version:Number(newVersion)}}
async function storedDocument(userId:string,ref:string){let data:any=null;const columns="id,storage_path,client_ref,mime_type";if(/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(ref)){const r=await admin.from("documents").select(columns).eq("user_id",userId).eq("id",ref).maybeSingle();if(r.error)throw r.error;data=r.data}if(!data){const r=await admin.from("documents").select(columns).eq("user_id",userId).eq("client_ref",ref).limit(1).maybeSingle();if(r.error)throw r.error;data=r.data}if(!data)throw new Error("DOCUMENT_NOT_FOUND");const {data:file,error:se}=await admin.storage.from("kwinest-documents").download(data.storage_path);if(se||!file)throw se||new Error("DOCUMENT_NOT_FOUND");const bytes=new Uint8Array(await file.arrayBuffer());if(bytes.byteLength>15*1024*1024)throw new Error("DOCUMENT_TOO_LARGE");return {row:data,bytes}}
async function duplicateCandidate(userId:string,b:any){const ref=safe(b.document_ref,240);if(!ref)throw new Error("DOCUMENT_REF_REQUIRED");const stored=await storedDocument(userId,ref),candidate=normalizeDuplicateFingerprint({document_ref:ref,document_sha256:await docSha(stored.bytes),perceptual_hash:safe(b.perceptual_hash,32),supplier_fingerprint:b.supplier?await supplierFingerprint(b.supplier):"",document_date:safe(b.document_date,10),gross_cents:b.gross_cents,vat_cents:b.vat_cents,text_fingerprint:b.ocr_text?await textFingerprint(b.ocr_text):"",document_type:safe(b.document_type||stored.row.mime_type,80)});const {data,error}=await admin.from("document_duplicate_fingerprints").select("*").eq("user_id",userId).neq("document_ref",ref).limit(200);if(error)throw error;return {candidate,candidates:findDuplicateCandidates(candidate,data||[],{limit:5})}}
async function duplicateRegister(userId:string,b:any){const r=await duplicateCandidate(userId,b);const {error}=await admin.from("document_duplicate_fingerprints").upsert({user_id:userId,...r.candidate},{onConflict:"user_id,document_ref"});if(error)throw error;return {registered:true,candidates:r.candidates,state:r.candidates.length?"possible_duplicate":"distinct"}}
async function ubl(userId:string,b:any,store:boolean){const xml=String(b.content||""),bytes=new TextEncoder().encode(xml).byteLength;if(!bytes)throw new Error("XML_EMPTY");if(bytes>MAX_UBL)throw new Error("XML_TOO_LARGE");const guard=secureXmlPreflight(xml,{maxBytes:MAX_UBL,maxDepth:80});if(!guard.ok)throw new Error(guard.errors[0]);const wf=XMLValidator.validate(xml),wfErrors=xmlErrors(wf);if(wf!==true)return {status:"invalid",ruleset:"UBL 2.1",layers:{xml:{valid:false,errors:wfErrors}},errors:wfErrors,warnings:[],financial_snapshot:null};const xsd:any=validateXsd(xml);const sem=validateUblSemantics(parser().parse(xml),xml),xsdErrors=(xsd.errors||[]).slice(0,100).map((e:any)=>({code:"UBL_XSD",message:safe(e.message||e,400)})),errors=xsdErrors.concat(sem.errors),warnings=sem.warnings.concat(sem.peppol.warnings),status=errors.length||sem.peppol.errors.length?"invalid":warnings.length?"needs_review":"valid";const result={status,ruleset:"OASIS UBL 2.1 XSD + BOEKUNA EN16931/Peppol safety subset 2026-09",layers:{xml:{valid:true},xsd:{valid:!!xsd.valid,root:safe(xsd.root,80),errors:xsdErrors},business:{valid:!sem.errors.length,errors:sem.errors,warnings:sem.warnings},peppol_subset:{valid:!sem.peppol.errors.length,errors:sem.peppol.errors,warnings:sem.peppol.warnings}},errors:errors.concat(sem.peppol.errors),warnings,financial_snapshot:sem.financial_snapshot,document:sem.document};if(store){const ref=safe(b.document_ref,240);if(!ref)throw new Error("DOCUMENT_REF_REQUIRED");const {error}=await admin.from("document_validation_results").insert({user_id:userId,document_ref:ref,validation_type:"peppol-bis-billing",status:result.status,ruleset:result.ruleset,source_sha256:await docSha(new TextEncoder().encode(xml)),errors:result.errors,warnings:result.warnings,financial_snapshot:result.financial_snapshot});if(error)throw error}return result}

Deno.serve(async(req:Request)=>{const ref=crypto.randomUUID(),started=performance.now();try{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(req)});const origin=req.headers.get("origin")||"";if(origin&&!ORIGINS.has(origin))return fail(req,"PERMISSION_DENIED",403,ref);if(req.method!=="POST")return fail(req,"METHOD_NOT_ALLOWED",405,ref);if(!ENABLED)return fail(req,"FEATURE_DISABLED",503,ref);const ctx=await auth(req);if(!ctx)return fail(req,"AUTH_SESSION_EXPIRED",401,ref);const b=await body(req),action=safe(b.action,60);if(!LIMITS[action])return fail(req,"INVALID_ACTION",400,ref);await rate(ctx.user.id,action);const mutations=new Set(["bank_commit","match_suggest","match_confirm","duplicate_register","ubl_validate_store"]);if(mutations.has(action)&&!(await canOperate(ctx.userClient)))return fail(req,"ACCOUNT_READ_ONLY",403,ref);let result:any;if(action==="iban_validate")result={iban:b.ocr?analyzeOcrIban(b.iban):validateIban(b.iban),bic:b.bic?validateBic(b.bic,b.iban):null};else if(action==="bank_preview")result=await bankPreview(ctx.user.id,b);else if(action==="bank_commit")result=await bankCommit(ctx.user.id,b);else if(action==="match_suggest")result=await suggestions(ctx.user.id,ctx.userClient,b);else if(action==="match_confirm")result=await confirm(ctx.user.id,ctx.userClient,b);else if(action==="duplicate_check")result=await duplicateCandidate(ctx.user.id,b);else if(action==="duplicate_register")result=await duplicateRegister(ctx.user.id,b);else if(action==="ubl_validate"||action==="ubl_validate_store")result=await ubl(ctx.user.id,b,action==="ubl_validate_store");log(action,{user_ref:ctx.user.id,ok:true,duration_ms:Math.round(performance.now()-started),transaction_count:Array.isArray(result&&result.transactions)?result.transactions.length:undefined,result_count:Array.isArray(result&&result.results)?result.results.length:undefined,duplicate_count:Array.isArray(result&&result.candidates)?result.candidates.length:undefined});return out(req,{ok:true,...result})}catch(e:any){const code=safe(e&&e.message||"UNKNOWN",80).replace(/[^A-Z0-9_/-]/gi,"_").toUpperCase(),status:any={REQUEST_TOO_LARGE:413,INVALID_JSON:400,BANK_FILE_ALREADY_IMPORTED:409,LEDGER_VERSION_CONFLICT:409,BANK_FORMAT_UNSUPPORTED:415,BANK_FILE_TOO_LARGE:413,BANK_TOO_MANY_TRANSACTIONS:413,XML_TOO_LARGE:413,DOCUMENT_TOO_LARGE:413,DOCUMENT_NOT_FOUND:404,MATCH_ALREADY_CONFIRMED:409,MANUAL_PAYMENT_NOT_FOUND:404,INVALID_MANUAL_PAYMENT_LINK:400,RATE_LIMITED:429,RATE_LIMIT_UNAVAILABLE:503,ENTITLEMENT_CHECK_FAILED:503}[code]||400;log("error",{error_code:code,reference_id:ref,duration_ms:Math.round(performance.now()-started)});return fail(req,code,status,ref)}});
